### ISSUE TITLE
Hard drives -> check hard drives status - situation when the disk usage file missing

### ISSUE THREAD

**Issue by hdevillepoix** [CPedersen3245/Desert-Fireball-Maintainence-GUI#2]
```Checking system status...```
```500 Internal Server Error: Error reading disk usage log file.```
... regardless the value in the disk usage file /tmp/dfn_disk_usage, update at usage status - to get fresh data
    (command: ```df -h | egrep "Filesystem|data"```)
    (for dives not currently mounted use value from the /tmp/dfn_disk_usage file)

**Comment by CPedersen3245** [comment]
Resolved! System now only checks for the dfn_disk_usage file if the drives are not mounted. If the file doesn't exist WHILE the drives are unmounted, the user is notified of this, and told to power + mount external HDDs.
