### ISSUE TITLE
camera full of data - situation in the field

### ISSUE THREAD

**Issue by hdevillepoix** [CPedersen3245/Desert-Fireball-Maintainence-GUI#3]
##     /data0 is full
we need some [button] to clear it - move to /data1+ as much as possible - TBD

##    memory card in DSLR full
data shall be moved to /data0 as part of the interval control test, but there must be enough space on /data0 - TBD

**Comment by CPedersen3245** [comment]
/data0 move button has been implemented. DSLR card warning before interval control test will be next.

**Comment by CPedersen3245** [comment]
Popup when performing interval control with the CF card image count implemented. Closed!
