### ISSUE TITLE
DFNEXT magnetic drives management

### ISSUE THREAD

**Issue by hdevillepoix** [CPedersen3245/Desert-Fireball-Maintainence-GUI#4]
## add to system
1.  power ON
2. ```sleep 15```
3. re-scan SATA/SCSI hotswap drives
        ```for i in $(find /sys/class/scsi_host/ -name host* ); do echo '- - -' > $i/scan; done```
4. ```sleep 1```
5. mount all
```mount -a ```

## remove from system
1. ```umount /data1 /data2 /data3```
2. tell the kernel to forget about the disks block devices  (assuming drives devices are /dev/sdb, /dev/sdc and /dev sdd)
    ```echo 1 > /sys/block/sdb/device/delete```
    ```echo 1 > /sys/block/sdc/device/delete```
    ```echo 1 > /sys/block/sdd/device/delete```
3. ```sleep 1```
4. power off

But there is one possible issue: we want to be sure not to delete the system SSD from the system.

That could happen if the magnetic data drives were powered at the system boot time (which is not nominal behaviour, but...)

It would be sudden system death to do that echo 1 > /sys/block/sdb/device/delete
command if the system SSD was for some reason not /dev/sda.

Even with mSATA/miniPCIe SSD, the system SSD device is not /dev/sda consistently - depends on what HDDs are connected to which SATA ports (in case they are powered during boot) - and in future, we will switch to SATA SSDs whihc will make it even more complicated.

So either we can exclude the situation of possible (warm?) reboot with data drives powered - or, otherwise the safe way is to check what the device is the system SSD, eg by using one of these methods:
1. lsblk or df -h, grep device size, if  in T (Terabytes), it is most likely magnetic data HDD
        or

2. lsblk, check how many partitions are on the device (removable devices: only one, system SSD: 3 or more)
        or 

3. smartctl -i /dev/sdX, grep "Rotation Rate:", either Solid State Drive or some number for rpm:
    -->    Rotation Rate:    Solid State Device
    -->    Rotation Rate:    5700 rpm 

    (I like the 3rd one most - should work unless we start using SSDs for data drives...)

**Comment by CPedersen3245** [comment]
Power ON routine changed, power off routine will be changed shortly.

**Comment by CPedersen3245** [comment]
And, power off routine changed to check for drive correctness. Issue closed!
