### ISSUE TITLE
Drives formatting - probe gives a hint regarding recommended formatting command

### ISSUE THREAD

**Issue by hdevillepoix** [CPedersen3245/Desert-Fireball-Maintainence-GUI#5]
MC: I'm still working on this one - but should work like this:

```/root/bin/dfn_setup_data_hdds.sh -p```
Probe result: DFNEXT SATA /dev/sdb data1 /dev/sdc data2
Suggested command to format all drives: ```/root/bin/dfn_setup_data_hdds.sh /dev/sdb data1 /dev/sdc data2 /dev/sdd data3```

**Comment by CPedersen3245** [comment]
Waiting on formatting script to be finalised

**Comment by CPedersen3245** [comment]
Updated, but yet to be tested.
